In [1]:
 from sklearn.neural_network import MLPClassifier
import os
import numpy as np
import pandas as pd
import urllib
import tensorflow as tf
from math import floor,ceil
dataLocTrain="data/updatedLoan.csv"
trainingdata = pd.read_csv(dataLocTrain)

In [2]:
trainingdata.head()

,loan_amnt,term,int_rate,installment,sub_grade,emp_length,annual_inc,dti,delinq_2yrs,open_acc,...,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding
0,5000,36,10.65,162.87,6,10,24000,27.65,0,3,...,0,0,0,0,0,0,0,0,0,0
1,2500,60,15.27,59.83,13,1,30000,1.00,0,3,...,0,0,0,0,0,0,0,0,0,0
2,2400,36,15.96,84.33,14,10,12252,8.72,0,2,...,0,0,0,0,0,0,0,1,0,0
3,10000,36,13.49,339.31,10,10,49200,20.00,0,10,...,0,0,0,0,0,1,0,0,0,0
4,3000,60,12.69,67.79,9,1,80000,17.94,0,15,...,0,0,0,0,0,1,0,0,0,0

In [3]:
trainingdata.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
loan_amnt,887350.0,14755.619260,8435.354701,500.00,8000.00,13000.000000,20000.000,3.500000e+04
term,887350.0,43.201325,10.998766,36.00,36.00,36.000000,60.000,6.000000e+01
int_rate,887350.0,13.246866,4.381873,5.32,9.99,12.990000,16.200,2.899000e+01
installment,887350.0,436.727404,244.183611,15.67,260.73,382.550000,572.600,1.445460e+03
sub_grade,887350.0,10.960066,6.493021,0.00,6.00,10.000000,15.000,3.400000e+01
emp_length,887350.0,5.784844,3.695749,0.00,2.00,6.000000,10.000,1.000000e+01
annual_inc,887350.0,75027.690610,64698.301292,0.00,45000.00,65000.000000,90000.000,9.500000e+06
dti,887350.0,18.157379,17.190784,0.00,11.91,17.660000,23.950,9.999000e+03
delinq_2yrs,887350.0,0.314442,0.862244,0.00,0.00,0.000000,0.000,3.900000e+01
open_acc,887350.0,11.548469,5.317313,0.00,8.00,11.000000,14.000,9.000000e+01
total_acc,887350.0,25.268026,11.840561,1.00,17.00,24.000000,32.000,1.690000e+02
out_prncp,887350.0,8403.399479,8493.453201,0.00,0.00,6459.900000,13659.900,4.937286e+04
total_pymnt,887350.0,7558.933639,7871.336345,0.00,1914.59,4895.091615,10617.200,5.777758e+04
total_pymnt_inv,887350.0,7521.375418,7846.141361,0.00,1900.11,4862.335000,10566.345,5.777758e+04
acc_now_delinq,887350.0,0.004991,0.077625,0.00,0.00,0.000000,0.000,1.400000e+01
OwnerOf_MORTGAGE,887350.0,0.499859,0.500000,0.00,0.00,0.000000,1.000,1.000000e+00
OwnerOf_NONE,887350.0,0.000052,0.007200,0.00,0.00,0.000000,0.000,1.000000e+00
OwnerOf_OTHER,887350.0,0.000205,0.014320,0.00,0.00,0.000000,0.000,1.000000e+00
OwnerOf_OWN,887350.0,0.098573,0.298088,0.00,0.00,0.000000,0.000,1.000000e+00
OwnerOf_RENT,887350.0,0.401307,0.490163,0.00,0.00,0.000000,1.000,1.000000e+00
List_Status_w,887350.0,0.485187,0.499781,0.00,0.00,0.000000,1.000,1.000000e+00
Application_JOINT,887350.0,0.000576,0.023990,0.00,0.00,0.000000,0.000,1.000000e+00
verification_status_Source Verified,887350.0,0.371396,0.483178,0.00,0.00,0.000000,1.000,1.000000e+00
verification_status_Verified,887350.0,0.328023,0.469493,0.00,0.00,0.000000,1.000,1.000000e+00
purpose_credit_card,887350.0,0.232357,0.422336,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_debt_consolidation,887350.0,0.590764,0.491693,0.00,0.00,1.000000,1.000,1.000000e+00
purpose_educational,887350.0,0.000477,0.021828,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_home_improvement,887350.0,0.058409,0.234515,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_house,887350.0,0.004178,0.064499,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_major_purchase,887350.0,0.019470,0.138171,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_medical,887350.0,0.009624,0.097630,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_moving,887350.0,0.006101,0.077872,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_other,887350.0,0.048308,0.214416,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_renewable_energy,887350.0,0.000648,0.025448,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_small_business,887350.0,0.011694,0.107506,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_vacation,887350.0,0.005337,0.072861,0.00,0.00,0.000000,0.000,1.000000e+00
purpose_wedding,887350.0,0.002645,0.051361,0.00,0.00,0.000000,0.000,1.000000e+00

In [4]:
trainingdata.shape

(887350, 37)

In [5]:
X = trainingdata.drop('int_rate',axis=1)
y = np.asarray(trainingdata['int_rate'], dtype="|S6")

In [6]:
#Splitting the testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
#Data preprocessing
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [8]:
# Fit only to the training data
scaler.fit(X_train)

/anaconda2/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

/anaconda2/lib/python3.7/site-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.

/anaconda2/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
#Training the model
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(36,36,36),max_iter=1000)

In [ ]:
mlp.fit(X_train,y_train)

In [ ]:
"""y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)
clf
"""

In [ ]:
"""
def multilayer_network(X,weights,biases,keep_prob):
    '''
    X: Placeholder for data inputs
    weights: dictionary of weights
    biases: dictionary of bias values
    
    '''
    #first hidden layer with sigmoid activation
    # sigmoid(X*W+b)
    
    with tf.name_scope('layer1'):
        layer_1 = tf.add(tf.matmul(X,weights['h1']),biases['h1'])
        layer_1 = tf.nn.sigmoid(layer_1)
        layer_1 = tf.nn.dropout(layer_1,keep_prob)
    
    #second hidden layer
    with tf.name_scope('layer2'):
        layer_2 = tf.add(tf.matmul(layer_1,weights['h2']),biases['h2'])
        layer_2 = tf.nn.sigmoid(layer_2)
        layer_2 = tf.nn.dropout(layer_2,keep_prob)
    
    #output layer
    with tf.name_scope('output_layer'):
        out_layer = tf.matmul(layer_2,weights['out']) + biases['out']
        tf.summary.histogram("output_for_the_layer",out_layer)
    
    return out_layer
    """

In [ ]:
#defining the weights and biases dictionary
"""
with tf.name_scope("weights"):
    weights = {
        'h1': tf.Variable(tf.random_normal([n_inputs,n_hidden_1]),name='W_input'),
        'h2': tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2]),name='W_layer1'),
        'out': tf.Variable(tf.random_normal([n_hidden_2,n_classes]),name='W_layer2')
    }
    tf.summary.histogram("weights1",weights['h1'])
    tf.summary.histogram("weights2",weights['h2'])
    tf.summary.histogram("weights_out",weights['out'])
with tf.name_scope("biases"):
    biases = {
        'h1': tf.Variable(tf.random_normal([n_hidden_1]),name='b_input'),
        'h2': tf.Variable(tf.random_normal([n_hidden_2]),name='b_layer1'),
        'out': tf.Variable(tf.random_normal([n_classes]),name='b_layer2')
    }
    tf.summary.histogram("bias_input",biases['h1'])
    tf.summary.histogram("bias_layer1",biases['h2'])
    tf.summary.histogram("bias_layer2",biases['out'])
keep_prob = tf.placeholder("float")
"""